# Generated by Django 5.0.6 on 2024-05-13 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_job_contact_email_job_created_job_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='contact_email',
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('resume', models.FileField(null=True, upload_to='')),
                ('cover_letter', models.FileField(null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.job')),
            ],
        ),
    ]
