# Generated by Django 5.0.6 on 2024-05-13 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_job_contact_email_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
